---
 
- hosts: localhost
  become: yes

  tasks:
          - name: Update System.
            yum:
                    update_cache: yes

          - name: Install Tilix
            yum:
                    name: tilix
                    state: latest

          - name: Add code repository
            yum_repository:
                    name: VSCode
                    description: Visual Studio Code Repository
                    baseurl: https://packages.microsoft.com/yumrepos/vscode
                    enabled: 1
                    gpgcheck: 1
                    gpgkey: https://packages.microsoft.com/keys/microsoft.asc

          - name: Install VS Code
            yum:
                    name: code
                    state: present

          - name: Install Devops Tools
            yum:
             pkg:
                     - nodejs
                     - yarn
                     - chromium
                     - gwenview
                     - zeal
                     - snapd

          - name: Add Classic Library Snap
            command: ln -s /var/lib/snapd/snap /snap

          - name: Install Pycharm-Community
            snap:
              name: pycharm-community
              classic: yes
